os: Visual Studio 2017

version: 1.0.{build}.{branch}

init:
  - git config --global core.autocrlf input

install:
  # Install repo specific stuff here
before_build:
  - cmd: dotnet --version

  - cmd: dotnet restore ./src/HalKit/HalKit.csproj --verbosity m

build_script:
  - cmd: dotnet build --configuration release ./src/HalKit/HalKit.csproj

test:    
  - cmd: dotnet test ./tests/HalKit.Tests/HalKit.Tests.csproj

deploy:
  - provider: NuGet
    api_key:
      secure: op0ZZ3Hco6aF361F2tmCFCHe9lmLkB5P6CjYOwvSmL11DFjDsyqCEEH4LK7mDbLV
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true

  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: KkZc/MtbfhwnJ7sfv74IFidwvYQmKLlmrO9yp4ydi30A+0XAP9c5frqd6f6PEZ7J
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true

nuget:
  project_feed: true
  disable_publish_on_pr: true

artifacts:
  - path: '.\src\HalKit\bin\release\*.nupkg'
    name: Packages