name: HalKit - Deploy

on: workflow_dispatch

jobs:
  deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Create the package
      run: dotnet build --configuration Release src/HalKit/HalKit.csproj --no-restore
    - name: Publish the package to nuget.org
      run: dotnet nuget push -k "$env:NUGET_API_TOKEN" src/HalKit/bin/Release/HalKit.nupkg
      env:
        NUGET_API_TOKEN: ${{ secrets.NUGET_API_TOKEN }}
