name: HalKit - Deploy

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    env:
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_TOKEN}}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release src/HalKit/HalKit.csproj --no-restore
    - name: Create the package
      run: dotnet pack --configuration Release src/HalKit/HalKit.csproj --no-build --no-restore
    - name: Publish the package to nuget.org
      run: dotnet nuget push -k $env:NUGET_API_TOKEN src/HalKit/bin/Release/*.nupkg
      env:
        NUGET_API_TOKEN: ${{secrets.NUGET_API_TOKEN}}
